### PR TITLE
[SPARK-40969] Replace spark TGZ url with apache archive url

### PR DESCRIPTION
**Pull request by dcoliversun**
### What changes were proposed in this pull request?

This PR aims to replace spark TGZ url with apache archive url.

### Why are the changes needed?

```
#13 [linux/amd64 4/9] RUN set -ex;     export SPARK_TMP="$(mktemp -d)";     cd $SPARK_TMP;     wget -nv -O spark.tgz "https://dlcdn.apache.org/spark/spark-3.3.0/spark-3.3.0-bin-hadoop3.tgz";     wget -nv -O spark.tgz.asc "https://downloads.apache.org/spark/spark-3.3.0/spark-3.3.0-bin-hadoop3.tgz.asc";     export GNUPGHOME="$(mktemp -d)";     gpg --keyserver hkps://keys.openpgp.org --recv-key "80FB8EBE8EBA68504989703491B5DC815DBF10D3" ||     gpg --keyserver hkps://keyserver.ubuntu.com --recv-keys "80FB8EBE8EBA68504989703491B5DC815DBF10D3";     gpg --batch --verify spark.tgz.asc spark.tgz;     gpgconf --kill all;     rm -rf "$GNUPGHOME" spark.tgz.asc;         tar -xf spark.tgz --strip-components=1;     chown -R spark:spark .;     mv jars /opt/spark/;     mv bin /opt/spark/;     mv sbin /opt/spark/;     mv kubernetes/dockerfiles/spark/decom.sh /opt/;     mv examples /opt/spark/;     mv kubernetes/tests /opt/spark/;     mv data /opt/spark/;     mv python/pyspark /opt/spark/python/pyspark/;     mv python/lib /opt/spark/python/lib/;     cd ..;     rm -rf "$SPARK_TMP";
#0 0.132 ++ mktemp -d
#0 0.133 + export SPARK_TMP=/tmp/tmp.oEdW8CyP9h
#0 0.133 + SPARK_TMP=/tmp/tmp.oEdW8CyP9h
#0 0.133 + cd /tmp/tmp.oEdW8CyP9h
#0 0.133 + wget -nv -O spark.tgz https://dlcdn.apache.org/spark/spark-3.3.0/spark-3.3.0-bin-hadoop3.tgz
#0 0.152 https://dlcdn.apache.org/spark/spark-3.3.0/spark-3.3.0-bin-hadoop3.tgz:
#0 0.152 2022-10-31 04:06:44 ERROR 404: Not Found.
#13 ERROR: process "/bin/sh -c set -ex;     export SPARK_TMP=\"$(mktemp -d)\";     cd $SPARK_TMP;     wget -nv -O spark.tgz \"$SPARK_TGZ_URL\";     wget -nv -O spark.tgz.asc \"$SPARK_TGZ_ASC_URL\";     export GNUPGHOME=\"$(mktemp -d)\";     gpg --keyserver hkps://keys.openpgp.org --recv-key \"$GPG_KEY\" ||     gpg --keyserver hkps://keyserver.ubuntu.com --recv-keys \"$GPG_KEY\";     gpg --batch --verify spark.tgz.asc spark.tgz;     gpgconf --kill all;     rm -rf \"$GNUPGHOME\" spark.tgz.asc;         tar -xf spark.tgz --strip-components=1;     chown -R spark:spark .;     mv jars /opt/spark/;     mv bin /opt/spark/;     mv sbin /opt/spark/;     mv kubernetes/dockerfiles/spark/decom.sh /opt/;     mv examples /opt/spark/;     mv kubernetes/tests /opt/spark/;     mv data /opt/spark/;     mv python/pyspark /opt/spark/python/pyspark/;     mv python/lib /opt/spark/python/lib/;     cd ..;     rm -rf \"$SPARK_TMP\";" did not complete successfully: exit code: 8
```
Old url `https://dlcdn.apache.org/spark/spark-3.3.0/spark-3.3.0-bin-hadoop3.tgz` is not found. Better to use unity apache archive url.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

No need to add new tests.

### CODE REVIEW

**Review by Yikun — APPROVED** [review]
According ASF note for download link, the archive link is official URL, so LGTM.

Thanks!

[1] https://infra.apache.org/release-distribution.html#download-links

**Comment by Yikun** [comment]
also cc @zhengruifeng

**Review by HyukjinKwon — APPROVED** [review]

**Review by zhengruifeng — APPROVED** [review]
lgtm

**Comment by Yikun** [comment]
@HyukjinKwon @zhengruifeng @dcoliversun Thanks! Merged .

**Comment by dcoliversun** [comment]
Thanks for your review @HyukjinKwon @Yikun @zhengruifeng

**Pull request closed without merging**
