### PR TITLE
[SPARK-43372] Use ; instead of && when enable set -ex

### PR DESCRIPTION
**Pull request by Yikun**
### What changes were proposed in this pull request?
- Use ; instead of && when enable set -ex
- ./add-dockerfiles.sh 3.4.0 to apply changes

### Why are the changes needed?
Address DOI comments: `9. using set -ex means you can use ; instead of && (really only matters for complex expressions, like the || in the later RUN that does use ;)` 

https://github.com/docker-library/official-images/pull/13089#issuecomment-1533540388

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
CI passed

### CODE REVIEW

**Comment by Yikun** [comment]
cc @HyukjinKwon @zhengruifeng

**Comment by Yikun** [comment]
After this patch merged, I will update DOI patch to latest to have 2nd round review.

**Review by HyukjinKwon — APPROVED** [review]

**Comment by Yikun** [comment]
@HyukjinKwon Thanks, merged.

**Comment by zhengruifeng** [comment]
Late LGTM, thank you @Yikun

**Pull request closed without merging**
