### PR TITLE
[SPARK-40832][DOCS] Add README for spark-docker

### PR DESCRIPTION
**Pull request by Yikun**
### What changes were proposed in this pull request?
Add README for spark-docker

### Why are the changes needed?
Although the PR of DOI has not been merged yet, but we'd better to briefly explain what this repository does.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Preview manually:

image

### CODE REVIEW

**Comment by Yikun** [comment]
cc @HyukjinKwon

**Review by zhengruifeng — APPROVED** [review]
LGTM

**Comment by Yikun** [comment]
@zhengruifeng Yes, this is planned, as there are still any images published. So, I'll update the documentation when it's published.

**Review by HyukjinKwon — APPROVED** [review]

**Comment by Yikun** [comment]
@zhengruifeng @HyukjinKwon Thanks, merged

**Pull request closed without merging**
