### PR TITLE
[SPARK-45169] Add official image Dockerfile for Apache Spark 3.5.0

### PR DESCRIPTION
**Pull request by Yikun**
### What changes were proposed in this pull request?
Add Apache Spark 3.5.0 Dockerfiles.

- Add 3.5.0 GPG key
- Add .github/workflows/build_3.5.0.yaml
- `./add-dockerfiles.sh 3.5.0` to generate dockerfiles
- Add version and tag info
- Backport https://github.com/apache/spark/commit/1d2c338c867c69987d8ed1f3666358af54a040e3 and https://github.com/apache/spark/commit/0c7b4306c7c5fbdd6c577774f8172f82e1d23e3b entrypoint changes

### Why are the changes needed?
Apache Spark 3.5.0 released

### Does this PR introduce _any_ user-facing change?
Docker image will be published.

### How was this patch tested?
Add workflow and CI passed

### CODE REVIEW

**Comment by Yikun** [comment]
@xuanyuanking Hi, yuanjian, would you mind uploading your public key to opengpg accroding reference [1]?

[1] https://github.com/apache/spark-docker/pull/54#discussion_r1299986624

**Comment by xuanyuanking** [comment]
image
Thank you Yikun!

**Comment by Yikun** [comment]
@xuanyuanking I retriggered job, it works. I will merge this after all CI green.

**Comment by Yikun** [comment]
@xuanyuanking I retriggered job, it works. I will merge this after all CI green.

**Review by HyukjinKwon — APPROVED** [review]

**Comment by Yikun** [comment]
@HyukjinKwon @xuanyuanking Thanks, merged.

**Comment by Yikun** [comment]
Publish triggered: https://github.com/apache/spark-docker/actions/runs/6187109381

**Comment by HyukjinKwon** [comment]
Awesome!!

**Pull request closed without merging**
