### PR TITLE
[SPARK-40569][TESTS] Add smoke test in standalone cluster for spark-docker

### PR DESCRIPTION
**Pull request by dcoliversun**
### What changes were proposed in this pull request?

This PR aims to add smoke test in standalone cluster for spark-docker repo.

### Why are the changes needed?

Verify spark docker works normally in standalone cluster.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

New test in GA.

### CODE REVIEW

**Comment by dcoliversun** [comment]
```
#13 [linux/amd64 4/9] RUN set -ex;     export SPARK_TMP="$(mktemp -d)";     cd $SPARK_TMP;     wget -nv -O spark.tgz "https://dlcdn.apache.org/spark/spark-3.3.0/spark-3.3.0-bin-hadoop3.tgz";     wget -nv -O spark.tgz.asc "https://downloads.apache.org/spark/spark-3.3.0/spark-3.3.0-bin-hadoop3.tgz.asc";     export GNUPGHOME="$(mktemp -d)";     gpg --keyserver hkps://keys.openpgp.org --recv-key "80FB8EBE8EBA68504989703491B5DC815DBF10D3" ||     gpg --keyserver hkps://keyserver.ubuntu.com --recv-keys "80FB8EBE8EBA68504989703491B5DC815DBF10D3";     gpg --batch --verify spark.tgz.asc spark.tgz;     gpgconf --kill all;     rm -rf "$GNUPGHOME" spark.tgz.asc;         tar -xf spark.tgz --strip-components=1;     chown -R spark:spark .;     mv jars /opt/spark/;     mv bin /opt/spark/;     mv sbin /opt/spark/;     mv kubernetes/dockerfiles/spark/decom.sh /opt/;     mv examples /opt/spark/;     mv kubernetes/tests /opt/spark/;     mv data /opt/spark/;     mv python/pyspark /opt/spark/python/pyspark/;     mv python/lib /opt/spark/python/lib/;     cd ..;     rm -rf "$SPARK_TMP";
#0 0.132 ++ mktemp -d
#0 0.133 + export SPARK_TMP=/tmp/tmp.oEdW8CyP9h
#0 0.133 + SPARK_TMP=/tmp/tmp.oEdW8CyP9h
#0 0.133 + cd /tmp/tmp.oEdW8CyP9h
#0 0.133 + wget -nv -O spark.tgz https://dlcdn.apache.org/spark/spark-3.3.0/spark-3.3.0-bin-hadoop3.tgz
#0 0.152 https://dlcdn.apache.org/spark/spark-3.3.0/spark-3.3.0-bin-hadoop3.tgz:
#0 0.152 2022-10-31 04:06:44 ERROR 404: Not Found.
#13 ERROR: process "/bin/sh -c set -ex;     export SPARK_TMP=\"$(mktemp -d)\";     cd $SPARK_TMP;     wget -nv -O spark.tgz \"$SPARK_TGZ_URL\";     wget -nv -O spark.tgz.asc \"$SPARK_TGZ_ASC_URL\";     export GNUPGHOME=\"$(mktemp -d)\";     gpg --keyserver hkps://keys.openpgp.org --recv-key \"$GPG_KEY\" ||     gpg --keyserver hkps://keyserver.ubuntu.com --recv-keys \"$GPG_KEY\";     gpg --batch --verify spark.tgz.asc spark.tgz;     gpgconf --kill all;     rm -rf \"$GNUPGHOME\" spark.tgz.asc;         tar -xf spark.tgz --strip-components=1;     chown -R spark:spark .;     mv jars /opt/spark/;     mv bin /opt/spark/;     mv sbin /opt/spark/;     mv kubernetes/dockerfiles/spark/decom.sh /opt/;     mv examples /opt/spark/;     mv kubernetes/tests /opt/spark/;     mv data /opt/spark/;     mv python/pyspark /opt/spark/python/pyspark/;     mv python/lib /opt/spark/python/lib/;     cd ..;     rm -rf \"$SPARK_TMP\";" did not complete successfully: exit code: 8
```
Same issues in GA. @Yikun

**Comment by Yikun** [comment]
We need rebase this after https://github.com/apache/spark-docker/pull/22 merged, and PR itself looks good to me.

**Comment by Yikun** [comment]
Mind to rebase now? Thanks @dcoliversun

**Review by Yikun — APPROVED** [review]
LGTM, this just adds the standalone test, and all exsiting image pass the test. Compare to https://github.com/apache/spark-docker/pull/15 , this PR doesn't expose the port.

The network is still connected because `docker0` and `spark-net-brige` helps. So, as a plus test, it's good enough.

**Comment by Yikun** [comment]
If no more comments, I will merge this today.

**Comment by Yikun** [comment]
```
testing/run_tests.sh --image-url ghcr.io/yikun/spark-docker/spark:python3 --scala-version 2.12 --spark-version 3.3.0

===> Smoke test for ghcr.io/yikun/spark-docker/spark:python3 as root
===> Starting spark-master
===> Starting spark-worker
===> Waiting for spark-master to be ready...
===> spark-master is ready.
===> Waiting for spark-worker to be ready...
===> spark-worker is ready.
===> Starting spark-submit
// ...
Pi is roughly 3.140891570445785
==> Killing 2 orphaned container(s)... done.
===> Smoke test for ghcr.io/yikun/spark-docker/spark:python3 as non-root
===> Starting spark-master
===> Starting spark-worker
===> Waiting for spark-master to be ready...
===> spark-master is ready.
===> Waiting for spark-worker to be ready...
===> spark-worker is ready.
===> Starting spark-submit
// ...
Pi is roughly 3.140739570369785
// ...
==> Killing 2 orphaned container(s)... done.
Test successfully finished
```

Also retest it in my arm env.

**Comment by Yikun** [comment]
Merge to master

**Pull request closed without merging**
