### PR TITLE
[SPARK-40845] Add template support for SPARK_GPG_KEY and fix GPG verify

### PR DESCRIPTION
**Pull request by Yikun**
### What changes were proposed in this pull request?
This patch:
- Add template support for `SPARK_GPG_KEY`. 
- Fix a bug on GPG verified. (Change `||` to `;`)
- Use opengpg.org instead of gpg.com becasue it would be uploaded in [spark release process](https://spark.apache.org/release-process.html).

### Why are the changes needed?
Each version have specific GPG key to verified, so we need to set GPG version separately.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
CI passed
Run `./add-dockerfiles.sh 3.3.0` and see GPG set correctly

### CODE REVIEW

**Comment by Yikun** [comment]
```
$ gpg --keyserver hkps://keyserver.ubuntu.com --recv-keys 80FB8EBE8EBA68504989703491B5DC815DBF10D3
gpg: keyserver receive failed: No data
```

This patch is failed due to @MaxGekk gpg key (3.3.0 release manager) haven't be imported. But for other release, such as 3.3.1-rc it's OK.

I'm not sure how to import them, maybe @HyukjinKwon know?

**Comment by Yikun** [comment]
Also cc @holdenk , she found the GPG key is hard code and send a mail to me, thanks!

**Review by martin-g — APPROVED** [review]

**Comment by Yikun** [comment]
cc @HyukjinKwon @zhengruifeng Ready to go

**Review by zhengruifeng — APPROVED** [review]
LGTM, thank you guys

**Comment by Yikun** [comment]
@martin-g @zhengruifeng @holdenk Thanks all, merged.

**Pull request closed without merging**
