### PR TITLE
[SPARK-43148] Add Apache Spark 3.4.0 Dockerfiles

### PR DESCRIPTION
**Pull request by Yikun**
### What changes were proposed in this pull request?
Add Apache Spark 3.4.0 Dockerfiles.
- Add 3.4.0 GPG key
- Add .github/workflows/build_3.4.0.yaml
- ./add-dockerfiles.sh 3.4.0

### Why are the changes needed?
Apache Spark 3.4.0 released:
https://spark.apache.org/releases/spark-release-3-4-0.html

### Does this PR introduce _any_ user-facing change?
Yes in future, new image will publised in future (after DOI reviewed)

### How was this patch tested?
Add workflow and CI passed

### CODE REVIEW

**Comment by Yikun** [comment]
cc @xinrong-meng @HyukjinKwon

**Review by xinrong-meng — APPROVED** [review]

**Comment by xinrong-meng** [comment]
Thanks @Yikun , I linked that issue to [SPARK-42523](https://issues.apache.org/jira/browse/SPARK-42523) for future reference.

**Review by HyukjinKwon — APPROVED** [review]

**Review by viirya — APPROVED** [review]

**Comment by Yikun** [comment]
Thanks, will merge soon.

**Comment by Yikun** [comment]
@xinrong-meng @HyukjinKwon @zhengruifeng  @viirya Thanks all, merged to master.

**Pull request closed without merging**
